version: '3'

networks:
  portal_b2becommerce: null

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - portal_b2becommerce
  mysql:
    image: mysql
    container_name: mysql_commerce
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portaldb
      MYSQL_USER: portal
      MYSQL_PASSWORD: portal
      SERVICE_NAME: mysql
    networks:
      - portal_b2becommerce

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8002:9000"
    networks:
      - portal_b2becommerce

  composer:
    image: prooph/composer:8.1
    container_name: composer_commerce
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - portal_b2becommerce

  npm:
    image: node:20.11
    container_name: npm_commerce
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint:
      - npm

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - portal_b2becommerce
    depends_on:
      - mysql